name: rickandmortyapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  rick_and_morty_api: ^0.1.3
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  video_player: ^2.8.6
  firebase_storage: ^11.7.7
  file_picker: ^8.0.3
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
